/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-10-08 02:55:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
 
    if (session.getAttribute("username") == null) {
        response.sendRedirect("login.jsp");
        return;
    }

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>FinMan Dashboard</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/css-non-secured/dashboard.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"navbar\">\r\n");
      out.write("			<h1>FinMan</h1>\r\n");
      out.write("			<nav>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"#\">Home</a></li>\r\n");
      out.write("					<li><a href=\"#\">Stock Market</a></li>\r\n");
      out.write("					<li><a href=\"#\">Savings Plans</a></li>\r\n");
      out.write("					<li><a href=\"#\">Insurance Policies</a></li>\r\n");
      out.write("					<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/ProfileServlet\">Profile</a></li>\r\n");
      out.write("					<!-- Profile Link -->\r\n");
      out.write("					<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/LogoutServlet\">Logout</a></li>\r\n");
      out.write("					<!-- Logout Link -->\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"search-bar\">\r\n");
      out.write("			<input type=\"text\" placeholder=\"Search stocks or indices...\">\r\n");
      out.write("			<button>Search</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<main>\r\n");
      out.write("		<section class=\"content\">\r\n");
      out.write("			<!-- Real-Time Stock Prices -->\r\n");
      out.write("			<div class=\"box stock-prices\">\r\n");
      out.write("				<h2>Real-Time Stock Prices</h2>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>Apple Inc. (AAPL): <span>$145.57</span></li>\r\n");
      out.write("					<li>Tesla Inc. (TSLA): <span>$650.10</span></li>\r\n");
      out.write("					<li>Amazon.com Inc. (AMZN): <span>$3400.15</span></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Market Indices -->\r\n");
      out.write("			<div class=\"box market-indices\">\r\n");
      out.write("				<h2>Market Indices</h2>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>Dow Jones: <span>34,105.45</span></li>\r\n");
      out.write("					<li>NASDAQ: <span>13,495.55</span></li>\r\n");
      out.write("					<li>S&P 500: <span>4,081.34</span></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Top Gainers & Losers -->\r\n");
      out.write("			<div class=\"box top-gainers-losers\">\r\n");
      out.write("				<h2>Top Gainers & Losers</h2>\r\n");
      out.write("				<div class=\"gainers-losers\">\r\n");
      out.write("					<p>\r\n");
      out.write("						Top Gainer: <span>Stock XYZ (+12.75%)</span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						Top Loser: <span>Stock ABC (-4.55%)</span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<div class=\"graph-placeholder\">Graph Placeholder</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"footer-content\">\r\n");
      out.write("			<div class=\"quick-links\">\r\n");
      out.write("				<h3>Quick Links</h3>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"#\">Home</a></li>\r\n");
      out.write("					<li><a href=\"#\">About Us</a></li>\r\n");
      out.write("					<li><a href=\"#\">Services</a></li>\r\n");
      out.write("					<li><a href=\"#\">Investment Tips</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"market-insights\">\r\n");
      out.write("				<h3>Market Insights</h3>\r\n");
      out.write("				<p>Daily Reports</p>\r\n");
      out.write("				<p>Weekly Newsletters</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"contact-us\">\r\n");
      out.write("				<h3>Contact Us</h3>\r\n");
      out.write("				<p>123 Market Street, New York, NY</p>\r\n");
      out.write("				<p>Email: info@finman.com</p>\r\n");
      out.write("				<p>Phone: +1 234 567 890</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<p>&copy; 2024 FinMan. All rights reserved.</p>\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
